-- 1. Profiles table (linked to auth.users)
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade primary key,
  full_name text not null,
  phone_number text unique not null,
  district text not null,
  user_type text not null check (user_type in ('farmer', 'buyer', 'admin')),
  village text,
  profile_picture_url text,
  latitude float8,
  longitude float8,
  must_change_password boolean default false,
  suspended_until timestamptz,
  suspension_reason text,
  created_at timestamptz default now()
);

-- Enable RLS on profiles
alter table public.profiles enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where policyname = 'Public profiles are viewable by everyone.' and tablename = 'profiles') then
    create policy "Public profiles are viewable by everyone." on public.profiles for select using (true);
  end if;
  if not exists (select 1 from pg_policies where policyname = 'Users can insert their own profile.' and tablename = 'profiles') then
    create policy "Users can insert their own profile." on public.profiles for insert with check (auth.uid() = id);
  end if;
  if not exists (select 1 from pg_policies where policyname = 'Users can update own profile.' and tablename = 'profiles') then
    create policy "Users can update own profile." on public.profiles for update using (auth.uid() = id);
  end if;
end $$;

-- 2. Coffee Stock table
create table if not exists public.coffee_stock (
  id bigint generated by default as identity primary key,
  farmer_id uuid references public.profiles(id) on delete cascade not null,
  coffee_type text not null,
  quantity float8 not null, -- Total initial quantity
  quantity_remaining float8, -- How much is left (defaults to quantity)
  price_per_kg float8 not null,
  coffee_picture_url text,
  description text default '',
  is_sold boolean default false,
  created_at timestamptz default now()
);

-- Trigger to set initial quantity_remaining
create or replace function public.set_initial_quantity_remaining()
returns trigger as $$
begin
  if NEW.quantity_remaining is null then
    NEW.quantity_remaining := NEW.quantity;
  end if;
  return NEW;
end;
$$ language plpgsql;

drop trigger if exists on_coffee_stock_insert on public.coffee_stock;
create trigger on_coffee_stock_insert
  before insert on public.coffee_stock
  for each row execute procedure public.set_initial_quantity_remaining();

alter table public.coffee_stock enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where policyname = 'Coffee stock is viewable by everyone.' and tablename = 'coffee_stock') then
    create policy "Coffee stock is viewable by everyone." on public.coffee_stock for select using (true);
  end if;
  if not exists (select 1 from pg_policies where policyname = 'Farmers can manage their own stock.' and tablename = 'coffee_stock') then
    create policy "Farmers can manage their own stock." on public.coffee_stock for all using (auth.uid() = farmer_id);
  end if;
end $$;

-- 3. Messages table
create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  sender_id uuid references public.profiles(id) on delete cascade not null,
  receiver_id uuid references public.profiles(id) on delete cascade not null,
  text text not null,
  coffee_stock_id bigint references public.coffee_stock(id) on delete set null,
  is_read boolean default false,
  is_purchase_request boolean default false,
  purchase_request_data jsonb,
  created_at timestamptz default now()
);

alter table public.messages enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where policyname = 'Users can see their own messages.' and tablename = 'messages') then
    create policy "Users can see their own messages." on public.messages for select using (auth.uid() = sender_id or auth.uid() = receiver_id);
  end if;
  if not exists (select 1 from pg_policies where policyname = 'Users can send messages.' and tablename = 'messages') then
    create policy "Users can send messages." on public.messages for insert with check (auth.uid() = sender_id);
  end if;
  if not exists (select 1 from pg_policies where policyname = 'Users can update is_read status.' and tablename = 'messages') then
    create policy "Users can update is_read status." on public.messages for update using (auth.uid() = receiver_id);
  end if;
end $$;

-- 4. Reviews table
create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  reviewer_id uuid references public.profiles(id) on delete cascade not null,
  reviewed_user_id uuid references public.profiles(id) on delete cascade, -- Optional if review is for product
  coffee_stock_id bigint references public.coffee_stock(id) on delete cascade, -- Optional if review is for user
  rating float8 not null,
  review_text text not null,
  created_at timestamptz default now(),
  check (reviewed_user_id is not null or coffee_stock_id is not null)
);

alter table public.reviews enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where policyname = 'Reviews are viewable by everyone.' and tablename = 'reviews') then
    create policy "Reviews are viewable by everyone." on public.reviews for select using (true);
  end if;
  if not exists (select 1 from pg_policies where policyname = 'Users can write reviews.' and tablename = 'reviews') then
    create policy "Users can write reviews." on public.reviews for insert with check (auth.uid() = reviewer_id);
  end if;
end $$;

-- 5. Notifications table (Generic)
create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  title text not null,
  content text not null,
  type text not null, -- 'review', 'stock_update', etc.
  metadata jsonb, -- e.g., {"stock_id": 123}
  is_read boolean default false,
  created_at timestamptz default now()
);

alter table public.notifications enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where policyname = 'Users can see their own notifications.' and tablename = 'notifications') then
    create policy "Users can see their own notifications." on public.notifications for select using (auth.uid() = user_id);
  end if;
  if not exists (select 1 from pg_policies where policyname = 'Users can update their own notifications.' and tablename = 'notifications') then
    create policy "Users can update their own notifications." on public.notifications for update using (auth.uid() = user_id);
  end if;
end $$;

-- 6. Favorites table
create table if not exists public.favorites (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  favorite_user_id uuid references public.profiles(id) on delete cascade not null,
  created_at timestamptz default now(),
  unique(user_id, favorite_user_id),
  constraint favorites_favorite_user_id_fkey foreign key (favorite_user_id) references public.profiles(id)
);

alter table public.favorites enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where policyname = 'Users can manage their favorites.' and tablename = 'favorites') then
    create policy "Users can manage their favorites." on public.favorites for all using (auth.uid() = user_id);
  end if;
end $$;

-- 7. Interested Buyers table
create table if not exists public.interested_buyers (
  id bigint generated by default as identity primary key,
  coffee_stock_id bigint references public.coffee_stock(id) on delete cascade not null,
  buyer_id uuid references public.profiles(id) on delete cascade not null,
  seen_by_farmer boolean default false,
  created_at timestamptz default now(),
  unique(coffee_stock_id, buyer_id)
);

alter table public.interested_buyers enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where policyname = 'Users can see interests related to them.' and tablename = 'interested_buyers') then
    create policy "Users can see interests related to them." on public.interested_buyers for select using (
      auth.uid() = buyer_id or
      exists (
        select 1 from public.coffee_stock
        where id = coffee_stock_id and farmer_id = auth.uid()
      )
    );
  end if;
  if not exists (select 1 from pg_policies where policyname = 'Buyers can express interest.' and tablename = 'interested_buyers') then
    create policy "Buyers can express interest." on public.interested_buyers for insert with check (auth.uid() = buyer_id);
  end if;
  if not exists (select 1 from pg_policies where policyname = 'Farmers can update seen status.' and tablename = 'interested_buyers') then
    create policy "Farmers can update seen status." on public.interested_buyers for update using (
      exists (
        select 1 from public.coffee_stock
        where id = coffee_stock_id and farmer_id = auth.uid()
      )
    );
  end if;
end $$;

-- 8. Password Reset Requests table
create table if not exists public.password_resets (
  id bigint generated by default as identity primary key,
  phone_number text not null,
  handled boolean default false,
  handled_at timestamptz,
  handled_by_admin uuid references public.profiles(id),
  created_at timestamptz default now()
);

alter table public.password_resets enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where policyname = 'Anyone can request a password reset.' and tablename = 'password_resets') then
    create policy "Anyone can request a password reset." on public.password_resets for insert with check (true);
  end if;
  if not exists (select 1 from pg_policies where policyname = 'Admins can manage reset requests.' and tablename = 'password_resets') then
    create policy "Admins can manage reset requests." on public.password_resets for all using (
      exists (
        select 1 from public.profiles
        where id = auth.uid() and user_type = 'admin'
      )
    );
  end if;
  if not exists (select 1 from pg_policies where policyname = 'Anyone can view their own reset request.' and tablename = 'password_resets') then
    create policy "Anyone can view their own reset request." on public.password_resets for select using (true);
  end if;
end $$;

-- TRIGGER for automatic profile creation on signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, full_name, phone_number, district, user_type)
  values (
    new.id,
    new.raw_user_meta_data->>'full_name',
    new.raw_user_meta_data->>'phone_number',
    new.raw_user_meta_data->>'district',
    new.raw_user_meta_data->>'user_type'
  );
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- TRIGGER for notifying followers of new stock
create or replace function public.notify_followers_of_new_stock()
returns trigger as $$
begin
  insert into public.notifications (user_id, title, content, type, metadata)
  select
    f.user_id,
    'New Coffee Listing!',
    p.full_name || ' just posted a new ' || NEW.coffee_type || ' listing.',
    'stock_update',
    jsonb_build_object('stock_id', NEW.id)
  from public.favorites f
  join public.profiles p on p.id = NEW.farmer_id
  where f.favorite_user_id = NEW.farmer_id;

  return NEW;
end;
$$ language plpgsql security definer;

drop trigger if exists on_coffee_stock_created on public.coffee_stock;
create trigger on_coffee_stock_created
  after insert on public.coffee_stock
  for each row execute procedure public.notify_followers_of_new_stock();

-- TRIGGER for notifying users when a sale is completed
create or replace function public.notify_buyer_of_sale_completion()
returns trigger as $$
declare
  buyer_id uuid;
  farmer_name text;
begin
  -- When a message is updated to be marked as handled/completed (hypothetically via metadata)
  -- In this app, 'Complete Sale' updates coffee_stock.
  -- To notify a specific buyer, we should really update the message that initiated the request.

  -- Let's define that when purchase_request_data has "status": "completed" added to it.
  if (NEW.purchase_request_data->>'status' = 'completed' and (OLD.purchase_request_data->>'status' is null or OLD.purchase_request_data->>'status' != 'completed')) then

    buyer_id := NEW.sender_id;

    select full_name into farmer_name from public.profiles where id = NEW.receiver_id;

    insert into public.notifications (user_id, title, content, type, metadata)
    values (
      buyer_id,
      'Sale Completed!',
      'Farmer ' || farmer_name || ' has confirmed your purchase request.',
      'sale_completed',
      jsonb_build_object('message_id', NEW.id, 'farmer_id', NEW.receiver_id)
    );
  end if;

  return NEW;
end;
$$ language plpgsql security definer;

drop trigger if exists on_purchase_request_completed on public.messages;
create trigger on_purchase_request_completed
  after update on public.messages
  for each row execute procedure public.notify_buyer_of_sale_completion();

-- TRIGGER for notifying users when they receive a review
create or replace function public.notify_user_of_review()
returns trigger as $$
declare
  target_user_id uuid;
  reviewer_name text;
  review_type text;
begin
  -- Get reviewer name
  select full_name into reviewer_name from public.profiles where id = NEW.reviewer_id;

  if NEW.reviewed_user_id is not null then
    target_user_id := NEW.reviewed_user_id;
    review_type := 'user_review';
  else
    -- Get farmer_id from coffee_stock
    select farmer_id into target_user_id from public.coffee_stock where id = NEW.coffee_stock_id;
    review_type := 'product_review';
  end if;

  if target_user_id is not null then
    insert into public.notifications (user_id, title, content, type, metadata)
    values (
      target_user_id,
      'New Review Received!',
      reviewer_name || ' left you a ' || NEW.rating || '-star review.',
      'review',
      jsonb_build_object(
        'review_id', NEW.id,
        'reviewer_id', NEW.reviewer_id,
        'review_type', review_type,
        'coffee_stock_id', NEW.coffee_stock_id
      )
    );
  end if;

  return NEW;
end;
$$ language plpgsql security definer;

drop trigger if exists on_review_created on public.reviews;
create trigger on_review_created
  after insert on public.reviews
  for each row execute procedure public.notify_user_of_review();

-- TRIGGER for notifying farmers when a buyer shows interest
create or replace function public.notify_farmer_of_interest()
returns trigger as $$
declare
  target_farmer_id uuid;
  buyer_name text;
  coffee_name text;
begin
  -- Get the farmer ID and coffee type
  select farmer_id, coffee_type into target_farmer_id, coffee_name
  from public.coffee_stock where id = NEW.coffee_stock_id;

  -- Get the buyer name
  select full_name into buyer_name from public.profiles where id = NEW.buyer_id;

  if target_farmer_id is not null then
    insert into public.notifications (user_id, title, content, type, metadata)
    values (
      target_farmer_id,
      'New Product Interest!',
      buyer_name || ' is interested in your ' || coffee_name || '.',
      'interest',
      jsonb_build_object(
        'stock_id', NEW.coffee_stock_id,
        'buyer_id', NEW.buyer_id
      )
    );
  end if;

  return NEW;
end;
$$ language plpgsql security definer;

drop trigger if exists on_interest_created on public.interested_buyers;
create trigger on_interest_created
  after insert on public.interested_buyers
  for each row execute procedure public.notify_farmer_of_interest();

-- REALTIME CONFIGURATION
do $$
begin
  -- Ensure publication exists
  if not exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    create publication supabase_realtime;
  end if;

  -- Add tables to the supabase_realtime publication only if they are not already there
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'profiles') then
    alter publication supabase_realtime add table public.profiles;
  end if;
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'messages') then
    alter publication supabase_realtime add table public.messages;
  end if;
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'notifications') then
    alter publication supabase_realtime add table public.notifications;
  end if;
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'coffee_stock') then
    alter publication supabase_realtime add table public.coffee_stock;
  end if;
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'interested_buyers') then
    alter publication supabase_realtime add table public.interested_buyers;
  end if;
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'favorites') then
    alter publication supabase_realtime add table public.favorites;
  end if;
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'password_resets') then
    alter publication supabase_realtime add table public.password_resets;
  end if;
end $$;

-- Set replica identity to FULL for tracking updates
alter table public.profiles replica identity full;
alter table public.messages replica identity full;
alter table public.notifications replica identity full;
alter table public.coffee_stock replica identity full;
alter table public.interested_buyers replica identity full;
alter table public.password_resets replica identity full;

-- 9. STORAGE CONFIGURATION
-- Ensure the kaawa-media bucket exists and remains public
insert into storage.buckets (id, name, public)
values ('kaawa-media', 'kaawa-media', true)
on conflict (id) do update set public = excluded.public;

-- Storage Policies for kaawa-media
do $$
begin
  -- Policy for public access to media
  if not exists (select 1 from pg_policies where policyname = 'Public Access' and tablename = 'objects' and schemaname = 'storage') then
    create policy "Public Access" on storage.objects for select using (bucket_id = 'kaawa-media');
  end if;

  -- Policy for users to upload their own profile pictures (path: profiles/{user_id}/{filename})
  if not exists (select 1 from pg_policies where policyname = 'Users can upload their own profile pictures' and tablename = 'objects' and schemaname = 'storage') then
    create policy "Users can upload their own profile pictures" on storage.objects for insert with check (
      bucket_id = 'kaawa-media' and (storage.foldername(name))[1] = 'profiles' and (storage.foldername(name))[2] = auth.uid()::text
    );
  end if;

  -- Policy for users to update their own profile pictures
  if not exists (select 1 from pg_policies where policyname = 'Users can update their own profile pictures' and tablename = 'objects' and schemaname = 'storage') then
    create policy "Users can update their own profile pictures" on storage.objects for update using (
      bucket_id = 'kaawa-media' and (storage.foldername(name))[1] = 'profiles' and (storage.foldername(name))[2] = auth.uid()::text
    );
  end if;

  -- Policy for users to delete their own profile pictures
  if not exists (select 1 from pg_policies where policyname = 'Users can delete their own profile pictures' and tablename = 'objects' and schemaname = 'storage') then
    create policy "Users can delete their own profile pictures" on storage.objects for delete using (
      bucket_id = 'kaawa-media' and (storage.foldername(name))[1] = 'profiles' and (storage.foldername(name))[2] = auth.uid()::text
    );
  end if;

  -- Policy for farmers to upload stock images (path: stock/{user_id}/{filename})
  if not exists (select 1 from pg_policies where policyname = 'Farmers can upload stock images' and tablename = 'objects' and schemaname = 'storage') then
    create policy "Farmers can upload stock images" on storage.objects for insert with check (
      bucket_id = 'kaawa-media' and (storage.foldername(name))[1] = 'stock' and (storage.foldername(name))[2] = auth.uid()::text
    );
  end if;

  -- Policy for farmers to update stock images
  if not exists (select 1 from pg_policies where policyname = 'Farmers can update stock images' and tablename = 'objects' and schemaname = 'storage') then
    create policy "Farmers can update stock images" on storage.objects for update using (
      bucket_id = 'kaawa-media' and (storage.foldername(name))[1] = 'stock' and (storage.foldername(name))[2] = auth.uid()::text
    );
  end if;

  -- Policy for farmers to delete stock images
  if not exists (select 1 from pg_policies where policyname = 'Farmers can delete stock images' and tablename = 'objects' and schemaname = 'storage') then
    create policy "Farmers can delete stock images" on storage.objects for delete using (
      bucket_id = 'kaawa-media' and (storage.foldername(name))[1] = 'stock' and (storage.foldername(name))[2] = auth.uid()::text
    );
  end if;
end $$;
