-- 1. Profiles table (linked to auth.users)
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade primary key,
  full_name text not null,
  phone_number text unique not null,
  district text not null,
  user_type text not null check (user_type in ('farmer', 'buyer', 'admin')),
  village text,
  profile_picture_url text,
  latitude float8,
  longitude float8,
  must_change_password boolean default false,
  suspended_until timestamptz,
  suspension_reason text,
  created_at timestamptz default now()
);

-- Enable RLS on profiles
alter table public.profiles enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where policyname = 'Public profiles are viewable by everyone.' and tablename = 'profiles') then
    create policy "Public profiles are viewable by everyone." on public.profiles for select using (true);
  end if;
  if not exists (select 1 from pg_policies where policyname = 'Users can insert their own profile.' and tablename = 'profiles') then
    create policy "Users can insert their own profile." on public.profiles for insert with check (auth.uid() = id);
  end if;
  if not exists (select 1 from pg_policies where policyname = 'Users can update own profile.' and tablename = 'profiles') then
    create policy "Users can update own profile." on public.profiles for update using (auth.uid() = id);
  end if;
end $$;

-- 2. Coffee Stock table
create table if not exists public.coffee_stock (
  id bigint generated by default as identity primary key,
  farmer_id uuid references public.profiles(id) on delete cascade not null,
  coffee_type text not null,
  quantity float8 not null,
  price_per_kg float8 not null,
  coffee_picture_url text,
  description text default '',
  is_sold boolean default false,
  created_at timestamptz default now()
);

alter table public.coffee_stock enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where policyname = 'Coffee stock is viewable by everyone.' and tablename = 'coffee_stock') then
    create policy "Coffee stock is viewable by everyone." on public.coffee_stock for select using (true);
  end if;
  if not exists (select 1 from pg_policies where policyname = 'Farmers can manage their own stock.' and tablename = 'coffee_stock') then
    create policy "Farmers can manage their own stock." on public.coffee_stock for all using (auth.uid() = farmer_id);
  end if;
end $$;

-- 3. Messages table
create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  sender_id uuid references public.profiles(id) on delete cascade not null,
  receiver_id uuid references public.profiles(id) on delete cascade not null,
  text text not null,
  coffee_stock_id bigint references public.coffee_stock(id) on delete set null,
  is_read boolean default false,
  is_purchase_request boolean default false,
  purchase_request_data jsonb,
  created_at timestamptz default now()
);

alter table public.messages enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where policyname = 'Users can see their own messages.' and tablename = 'messages') then
    create policy "Users can see their own messages." on public.messages for select using (auth.uid() = sender_id or auth.uid() = receiver_id);
  end if;
  if not exists (select 1 from pg_policies where policyname = 'Users can send messages.' and tablename = 'messages') then
    create policy "Users can send messages." on public.messages for insert with check (auth.uid() = sender_id);
  end if;
  if not exists (select 1 from pg_policies where policyname = 'Users can update is_read status.' and tablename = 'messages') then
    create policy "Users can update is_read status." on public.messages for update using (auth.uid() = receiver_id);
  end if;
end $$;

-- 4. Reviews table
create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  reviewer_id uuid references public.profiles(id) on delete cascade not null,
  reviewed_user_id uuid references public.profiles(id) on delete cascade not null,
  rating float8 not null,
  review_text text not null,
  created_at timestamptz default now(),
  unique(reviewer_id, reviewed_user_id)
);

alter table public.reviews enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where policyname = 'Reviews are viewable by everyone.' and tablename = 'reviews') then
    create policy "Reviews are viewable by everyone." on public.reviews for select using (true);
  end if;
  if not exists (select 1 from pg_policies where policyname = 'Users can write reviews.' and tablename = 'reviews') then
    create policy "Users can write reviews." on public.reviews for insert with check (auth.uid() = reviewer_id);
  end if;
end $$;

-- 5. Review Notifications table
create table if not exists public.review_notifications (
  id bigint generated by default as identity primary key,
  review_id bigint references public.reviews(id) on delete cascade not null,
  recipient_id uuid references public.profiles(id) on delete cascade not null,
  sender_id uuid references public.profiles(id) on delete cascade not null,
  message text not null,
  is_read boolean default false,
  created_at timestamptz default now()
);

alter table public.review_notifications enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where policyname = 'Recipients can see their review notifications.' and tablename = 'review_notifications') then
    create policy "Recipients can see their review notifications." on public.review_notifications for select using (auth.uid() = recipient_id);
  end if;
  if not exists (select 1 from pg_policies where policyname = 'Senders can insert review notifications.' and tablename = 'review_notifications') then
    create policy "Senders can insert review notifications." on public.review_notifications for insert with check (auth.uid() = sender_id);
  end if;
  if not exists (select 1 from pg_policies where policyname = 'Recipients can update is_read status.' and tablename = 'review_notifications') then
    create policy "Recipients can update is_read status." on public.review_notifications for update using (auth.uid() = recipient_id);
  end if;
end $$;

-- 6. Favorites table
create table if not exists public.favorites (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  favorite_user_id uuid references public.profiles(id) on delete cascade not null,
  created_at timestamptz default now(),
  unique(user_id, favorite_user_id)
);

alter table public.favorites enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where policyname = 'Users can manage their favorites.' and tablename = 'favorites') then
    create policy "Users can manage their favorites." on public.favorites for all using (auth.uid() = user_id);
  end if;
end $$;

-- 7. Interested Buyers table
create table if not exists public.interested_buyers (
  id bigint generated by default as identity primary key,
  coffee_stock_id bigint references public.coffee_stock(id) on delete cascade not null,
  buyer_id uuid references public.profiles(id) on delete cascade not null,
  seen_by_farmer boolean default false,
  created_at timestamptz default now(),
  unique(coffee_stock_id, buyer_id)
);

alter table public.interested_buyers enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where policyname = 'Users can see interests related to them.' and tablename = 'interested_buyers') then
    create policy "Users can see interests related to them." on public.interested_buyers for select using (
      auth.uid() = buyer_id or
      exists (
        select 1 from public.coffee_stock
        where id = coffee_stock_id and farmer_id = auth.uid()
      )
    );
  end if;
  if not exists (select 1 from pg_policies where policyname = 'Buyers can express interest.' and tablename = 'interested_buyers') then
    create policy "Buyers can express interest." on public.interested_buyers for insert with check (auth.uid() = buyer_id);
  end if;
  if not exists (select 1 from pg_policies where policyname = 'Farmers can update seen status.' and tablename = 'interested_buyers') then
    create policy "Farmers can update seen status." on public.interested_buyers for update using (
      exists (
        select 1 from public.coffee_stock
        where id = coffee_stock_id and farmer_id = auth.uid()
      )
    );
  end if;
end $$;

-- 8. Password Reset Requests table
create table if not exists public.password_resets (
  id bigint generated by default as identity primary key,
  phone_number text not null,
  handled boolean default false,
  handled_at timestamptz,
  handled_by_admin uuid references public.profiles(id),
  created_at timestamptz default now()
);

alter table public.password_resets enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where policyname = 'Anyone can request a password reset.' and tablename = 'password_resets') then
    create policy "Anyone can request a password reset." on public.password_resets for insert with check (true);
  end if;
  if not exists (select 1 from pg_policies where policyname = 'Admins can manage reset requests.' and tablename = 'password_resets') then
    create policy "Admins can manage reset requests." on public.password_resets for all using (
      exists (
        select 1 from public.profiles
        where id = auth.uid() and user_type = 'admin'
      )
    );
  end if;
end $$;

-- TRIGGER for automatic profile creation on signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, full_name, phone_number, district, user_type)
  values (
    new.id,
    new.raw_user_meta_data->>'full_name',
    new.raw_user_meta_data->>'phone_number',
    new.raw_user_meta_data->>'district',
    new.raw_user_meta_data->>'user_type'
  );
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- REALTIME CONFIGURATION
do $$
begin
  -- Add tables to the supabase_realtime publication only if they are not already there
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'messages') then
    alter publication supabase_realtime add table public.messages;
  end if;
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'review_notifications') then
    alter publication supabase_realtime add table public.review_notifications;
  end if;
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'coffee_stock') then
    alter publication supabase_realtime add table public.coffee_stock;
  end if;
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'interested_buyers') then
    alter publication supabase_realtime add table public.interested_buyers;
  end if;
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'password_resets') then
    alter publication supabase_realtime add table public.password_resets;
  end if;
end $$;

-- Set replica identity to FULL for tracking updates
alter table public.messages replica identity full;
alter table public.review_notifications replica identity full;
alter table public.coffee_stock replica identity full;
alter table public.interested_buyers replica identity full;
alter table public.password_resets replica identity full;

-- 9. STORAGE CONFIGURATION
-- Ensure the kaawa-media bucket exists
insert into storage.buckets (id, name, public)
values ('kaawa-media', 'kaawa-media', true)
on conflict (id) do nothing;

-- Storage Policies for kaawa-media
do $$
begin
  -- Policy for public access to media
  if not exists (select 1 from pg_policies where policyname = 'Public Access' and tablename = 'objects' and schemaname = 'storage') then
    create policy "Public Access" on storage.objects for select using (bucket_id = 'kaawa-media');
  end if;

  -- Policy for users to upload their own profile pictures (path: profiles/{user_id}/{filename})
  if not exists (select 1 from pg_policies where policyname = 'Users can upload their own profile pictures' and tablename = 'objects' and schemaname = 'storage') then
    create policy "Users can upload their own profile pictures" on storage.objects for insert with check (
      bucket_id = 'kaawa-media' and (storage.foldername(name))[1] = 'profiles' and (storage.foldername(name))[2] = auth.uid()::text
    );
  end if;

  -- Policy for users to update their own profile pictures
  if not exists (select 1 from pg_policies where policyname = 'Users can update their own profile pictures' and tablename = 'objects' and schemaname = 'storage') then
    create policy "Users can update their own profile pictures" on storage.objects for update using (
      bucket_id = 'kaawa-media' and (storage.foldername(name))[1] = 'profiles' and (storage.foldername(name))[2] = auth.uid()::text
    );
  end if;

  -- Policy for users to delete their own profile pictures
  if not exists (select 1 from pg_policies where policyname = 'Users can delete their own profile pictures' and tablename = 'objects' and schemaname = 'storage') then
    create policy "Users can delete their own profile pictures" on storage.objects for delete using (
      bucket_id = 'kaawa-media' and (storage.foldername(name))[1] = 'profiles' and (storage.foldername(name))[2] = auth.uid()::text
    );
  end if;

  -- Policy for farmers to upload stock images (path: stock/{user_id}/{filename})
  if not exists (select 1 from pg_policies where policyname = 'Farmers can upload stock images' and tablename = 'objects' and schemaname = 'storage') then
    create policy "Farmers can upload stock images" on storage.objects for insert with check (
      bucket_id = 'kaawa-media' and (storage.foldername(name))[1] = 'stock' and (storage.foldername(name))[2] = auth.uid()::text
    );
  end if;

  -- Policy for farmers to update stock images
  if not exists (select 1 from pg_policies where policyname = 'Farmers can update stock images' and tablename = 'objects' and schemaname = 'storage') then
    create policy "Farmers can update stock images" on storage.objects for update using (
      bucket_id = 'kaawa-media' and (storage.foldername(name))[1] = 'stock' and (storage.foldername(name))[2] = auth.uid()::text
    );
  end if;

  -- Policy for farmers to delete stock images
  if not exists (select 1 from pg_policies where policyname = 'Farmers can delete stock images' and tablename = 'objects' and schemaname = 'storage') then
    create policy "Farmers can delete stock images" on storage.objects for delete using (
      bucket_id = 'kaawa-media' and (storage.foldername(name))[1] = 'stock' and (storage.foldername(name))[2] = auth.uid()::text
    );
  end if;
end $$;
